# Use the official OpenJDK image as a base image
FROM openjdk:17-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from your local machine to the container
COPY target/music.jar /app/music.jar

# Expose the port your application will run on (if applicable)
EXPOSE 8080

# Define the command to run your application
ENTRYPOINT ["java", "-jar", "your-lucene-app.jar"]
